name: TagBot
on:
  schedule:
    - cron: 0 0 * * *
  pull_request:
    types:
      - closed
  workflow_dispatch:
jobs:
  TagBot:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: julia --project=.ci -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(; url="https://github.com/JuliaRegistries/RegistryCI.jl", rev="cdg/tagbot-fixup"))'
        env:
          JULIA_PKG_SERVER: ''
      - run: julia --project=.ci -e 'using RegistryCI.TagBot; TagBot.main()'
        env:
          GITHUB_TOKEN: ${{ secrets.TAGBOT_TOKEN }}
